point =12
def coffee_point(point):
    if point<10:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        print("포인트가 부족합니다.")
        print("무료 커피 흭득까지 {0}점 남았습니다.".format(10-point))
        print("무료커피 흭득까지 %d점 남았습니다." % (10-point))
        return point
    else:
        print("커피 포인트 사용이 완료")
        point-=10
        print("잔여 포인트는 {0}점 입니다.".format(point))
        return point

coffee_point(point)